Add translations ApidaeParser
GeotrekCE/Geotrek-admin pull request #2308
Opened 2020-08-07 16:07 UTC by LePetitTim

2021-02-17 06:58 UTC, gutard reviewed
Plutôt que de devoir définir autant de méthodes filter_xxx que de langues, je pense qu'il serait pertinent d'utiliser gettext.

D'autre part, ça me dérange un peu d'avoir des _fr dans la définition des champs alors que ça concerne toutes les langues.

Je pense qu'il faudrait intégrer la gestion des traductions directement dans le parser de base en y ajoutant une itération sur les langues, soit à l'extérieur, soit à l'intérieur de l'itération sur les objets.

Si tu veux savoir quels champs sont traduits dans un modèle tu peux utiliser `modeltranslation.translator.translator.get_options_for_model(<Model>).fields.keys()`.

2021-02-17 06:58 UTC, gutard commented on geotrek/tourism/parsers.py
> +            if not isinstance(value, str):
Ça serait plus correct et plus lisible avec `if isinstance(value, (list, tuple)):`

2021-02-17 08:57 UTC, LePetitTim commented on geotrek/tourism/parsers.py
> +            if not isinstance(value, str):
C'est pas bête d'utiliser les gettext.

2021-02-19 13:58 UTC, gutard reviewed
Pour moi l'idée ça serait de pouvoir écrire dans le parser un truc du genre :
```
    translate = True
    fields = {
        'description': 'presentation.descriptifDetaille.libelle{capitalized_language}',
    }
```
Et de faire la boucle sur MODELTRANSLATION_LANGUAGE dans Parser plutôt que dans ApidaeParser.

2022-01-24 13:48 UTC, Chatewgne requested changes

2022-06-16 12:30 UTC, Chatewgne commented on geotrek/tourism/parsers.py
> +        modif = "<i>" + _("Update sheet by ") + proprio + _(" the ") + datemodif + "</i>"
Toujours à changer

2022-12-01 10:41 UTC, closed without merging