Remove default_structure
GeotrekCE/Geotrek-admin pull request #2550
Opened 2021-02-16 16:32 UTC by LePetitTim

2021-02-17 06:20 UTC, gutard requested changes
Attention ! `Structure.objects.first()` ne renvoie pas ce que tu crois. 1) car il y a un `ordering = ['name']` défini dans le modèle donc ça trie par le nom et pas par le pk, et 2) car la définition pour la default_structure c'est 1 ce qui est différent du "plus petit pk qui existe dans la base".

Exemple sur la DB du PNE :
```
>>> Structure.objects.get(pk=1)
<Structure: PNE>
>>> Structure.objects.first()
<Structure: CDRP05>
```

D'autre part, pour améliorer la lisibilité, et gérer l'éventuel cas d'une instance déjà installée sur laquelle default_structure.pk != 1, je pense que ça serait pertinent d'ajouter un setting `DEFAULT_STRUCTURE_PK=1`.

2021-02-17 08:51 UTC, LePetitTim commented
Ok pour le .first()
> 
> D'autre part, pour améliorer la lisibilité, et gérer l'éventuel cas d'une instance déjà installée sur laquelle default_structure.pk != 1, je pense que ça serait pertinent d'ajouter un setting `DEFAULT_STRUCTURE_PK = 1`.

Est ce que dans ce cas, c'est pas mieux de mettre un db_index sur le name, garder le DEFAULT_STRUCTURE_NAME.
L'objectif premier c'est juste d'enlever les requetes faites dans le default. Si je met dans les migrations, default=DEFAULT_STRUCTURE_NAME. Il n'y aura pas de requete. Je peux quand meme garder le post_migration pour creer une structure avec DEFAULT_STRUCTURE_NAME.
Apres si l'objectif c'est juste qu'ils evitent de le changer dans le fichier de settings, le nouveau settings. Ok.

2021-02-17 09:13 UTC, gutard commented
> L'objectif premier c'est juste d'enlever les requetes faites dans le default.

Je ne suis pas d'accord. On a eu des tas de problèmes avec des gens qui ont changé le setting defaut_structure sans modifier dans l'admin et ça a foutu le bazar. Il faut absolument régler aussi ce point si on change quelque chose au default structure.

2021-02-17 12:52 UTC, gutard commented on geotrek/authent/admin.py
> +        if obj and Structure.objects.get(pk=settings.DEFAULT_STRUCTURE_PK) == obj:
Pourquoi pas simplement `if obj.pk == settings.DEFAULT_STRUCTURE_PK` ?

2021-02-17 12:52 UTC, gutard commented on geotrek/authent/admin.py
>          return True
Si l'utilisateur n'a pas le droit `can_delete_structure` ça devrait renvoyer `False`. Il faudrait appeler la méthode du super().

2021-02-17 12:52 UTC, gutard commented on geotrek/authent/apps.py
> +    if not Structure.objects.filter(pk=settings.DEFAULT_STRUCTURE_PK).exists():
Ça ne serait pas plus simple d'utiliser get_or_create() ?

2021-02-17 15:04 UTC, gutard commented on geotrek/authent/apps.py
> +        structure.save()
Ça ne fait pas ce qu'il faut. Si ta structure par défaut ne s'appelle pas 'My structure', ça va en créer une nouvelle. On veut plutôt faire `Structure.objects.get_or_create(pk=1, defaults={'name: 'My structure'})`.

Si une structure avec pk=1 existe, ça la retourne, peu importe son nom, et ça ne la modifie pas. Sinon, ça créer une nouvelle structure avec pk=1 et name='My structure'.

Au passage, on pourrait traduire.

2021-02-17 16:04 UTC, gutard approved these changes

2021-02-17 16:04 UTC, gutard commented on .circleci/config.yml
> +      - run: test $(ls geotrek/*/migrations/*.py | xargs grep -l -e structure | xargs grep -l default=1, | wc -l) -eq 0
OK bon c'est pas trop possible à faire correctement avec un grep.

2021-02-18 14:28 UTC, LePetitTim commented
Ne fonctionne pas avec le get_or_create(id=1, defaults={})

2021-02-19 13:31 UTC, gutard commented
> Ne fonctionne pas avec le get_or_create(id=1, defaults={})

Tu es sûr ? Je viens d'essayer :

```
>>> from geotrek.authent.models import Structure
>>> structure, created = Structure.objects.get_or_create(id=42, defaults={'name': 'New structure'})
>>> structure.pk, created
(42, True)
>>> structure, created = Structure.objects.get_or_create(id=42, defaults={'name': 'New structure'})
>>> structure.pk, created
(42, False)
```

2021-02-19 13:33 UTC, gutard commented on geotrek/authent/apps.py
> +    if created and not Structure.objects.filter(pk=1).exists():
Il faudrait utiliser settings.DEFAULT_STRUCTURE_PK plutôt que 1.

2021-02-26 13:49 UTC, babastienne approved these changes

2021-03-02 17:17 UTC, gutard requested changes

2021-03-02 17:17 UTC, gutard commented on geotrek/authent/apps.py
> +    structure, created = Structure.objects.get_or_create(name=_('My structure'))
Si la structure par défaut (celle avec pk=DEFAULT_STRUCTURE_PK) existe déjà mais a été renommée, cette ligne va recréer une nouvelle structure. Ce n'est pas ce qu'on veut. L'idée est que la structure par défaut soit définie par son **pk** et non plus par son nom. Ça permet d'éviter les problèmes de renommage qu'on a souvent rencontré par le passé.

Normalement, un `structure, create = Structure.objects.get_or_create(pk=DEFAULT_STRUCTURE_PK, defaults={'name': _('My structure')})` devrait faire ce qu'il faut.

2022-12-01 10:11 UTC, LePetitTim commented
Cache available for default structure since 2.92.0

* Need to be improved to set cache key as the name of the structure 
Without this, if you want to change default structure you need to clear cache. It will always keep the old default_structure pk

2022-12-01 10:11 UTC, closed without merging

2022-12-01 10:27 UTC, LePetitTim commented
https://github.com/GeotrekCE/Geotrek-admin/issues/3338