Simplify code thanks to Python 3
GeotrekCE/Geotrek-admin pull request #2571
Opened 2021-03-06 13:19 UTC by claudep

2021-03-06 13:49 UTC, gutard requested changes
Thanks. Could you fix the syntax problem in geotrek/core/urls.py please ?

2021-03-06 13:49 UTC, gutard commented on geotrek/core/urls.py
> +        return = super().get_queryset().prefetch_related('networks', 'usages')
Syntax error (`=` should be removed)

2021-03-06 15:16 UTC, claudep commented on geotrek/core/urls.py
> +        return = super().get_queryset().prefetch_related('networks', 'usages')
Done. Sorry, I'm still working on running tests locally...

2021-03-20 09:11 UTC, claudep commented
@gutard, as soon as you think it's time to push that patch, I'll gladly rebase the PR. Just tell me.

2021-03-23 14:29 UTC, gutard commented
Les tests unitaires ne passent pas. Il y a parfois quelques subtilités qui font qu'on ne peut pas supprimer les paramètres de  `super()` sans regarder d'un peu plus près. Par exemple dans la classe `LastModifiedMixin`.

2021-03-23 16:30 UTC, claudep commented
Oui, j'ai vu ça et j'en ai laissé quelques-uns, apparemment pas assez. Je vais examiner ça, maintenant que je peux lancer la plupart des tests en local.

2021-03-26 13:50 UTC, gutard approved these changes

2021-03-26 13:50 UTC, merged