Add map nginx conf multiple cors header
GeotrekCE/Geotrek-admin pull request #2672
Opened 2021-06-01 11:51 UTC by LePetitTim

2021-06-01 12:59 UTC, camillemonchicourt commented
Si certains ont surcouché leur fichier ``/opt/geotrek-admin/varconf/nginx.conf.in``, alors il faudra qu'ils reportent cette modification dans leur surcouche, après la prochaine mise à jour.

2021-06-03 08:02 UTC, submarcos approved these changes

2021-06-03 08:12 UTC, numahell requested changes
Some grammar suggestion

2021-06-03 08:12 UTC, numahell commented on docs/changelog.rst
> +- Template nginx.conf.in was changed to work with multiple rando portals (#2670).
```suggestion
- Template nginx.conf.in has been changed to work with multiple rando portals (#2670).
```

2021-06-03 08:12 UTC, numahell commented on docs/changelog.rst
> +First, if you changed file `/opt/geotrek-admin/var/conf/nginx.conf.in`, back it up somewhere.
```suggestion
First, if you have modified the `/opt/geotrek-admin/var/conf/nginx.conf.in` file, save it somewhere.
```

2021-06-03 08:12 UTC, numahell commented on docs/changelog.rst
> +2 - Copy your changes from the backed up file to the new version.
```suggestion
2 - Copy your changes from the saved file to the new version.
```

2021-06-03 08:12 UTC, numahell commented on docs/changelog.rst
> +3 - Execute : dpkg-reconfigure geotrek-admin to reapply your customization.
```suggestion
3 - Execute : `dpkg-reconfigure geotrek-admin` to reapply your customization.
```

2021-06-03 08:53 UTC, billux requested changes

2021-06-03 08:53 UTC, billux commented on debian/postinst
> +export RANDO_SERVER_NAME_PIPE="`echo "$RANDO_SERVER_NAME" | sed 's/ /|/g'`"
An HTTP request with `Origin: http://foo?http://valid-rando-domain` will be allowed by the regexp in the map if `valid-rando-domain` is set in $RANDO_SERVER_NAME. The regexp in $RANDO_SERVER_NAME_PIPE should strictly match Rando URLs, so I suggest you enclose the regexp with `^$` only if not empty and not `*`:

```suggestion
if [ -n "${RANDO_SERVER_NAME}" ] && [ "${RANDO_SERVER_NAME}" != "*" ]; then
    export RANDO_SERVER_NAME_PIPE="^`echo "$RANDO_SERVER_NAME" | sed 's/ /|/g'`$"
else
    export RANDO_SERVER_NAME_PIPE="`echo "$RANDO_SERVER_NAME" | sed 's/ /|/g'`"
fi
```

2021-06-03 12:09 UTC, Chatewgne approved these changes

2021-06-03 13:56 UTC, LePetitTim commented
I merge it when it is possible.

2021-06-07 07:32 UTC, merged