Exclus les pois spécifiés dans une rando lors du filtre par rando sur
GeotrekCE/Geotrek-admin pull request #2680
Opened 2021-06-04 10:23 UTC by babastienne

endpoint poi

2021-06-09 07:49 UTC, submarcos reviewed
question sur deleted=False

2021-06-09 07:49 UTC, submarcos commented on geotrek/api/v2/filters.py
> +                | Q(touristic_events__portal__in=portals.split(',')) & Q(touristic_events__deleted=False)
j'ai deja vu du code dans geotrek ou on regardeait si la qs avait l'attribut existing (deleted=False) et auquel cas on l'apellait. Ce qui générit automatiquement le & deleted=False. çà serait pas mieux / moins risqué d'en louper ?

2021-06-09 08:10 UTC, babastienne commented on geotrek/api/v2/filters.py
> +                | Q(touristic_events__portal__in=portals.split(',')) & Q(touristic_events__deleted=False)
Il existe en effet une propriété existing ajouté par le NoDeleteManager de Geotrek, mais qui verifie si l'attribut deleted=False uniquement sur les objets de la queryset. Là en l'occurence je cherche à vérifié que les objets associés (treks, touristiccontents, etc.) sont bien à deleted=False, et pas uniquement les objets de la qs.

2021-06-09 08:11 UTC, babastienne commented on geotrek/api/v2/filters.py
> +                | Q(touristic_events__portal__in=portals.split(',')) & Q(touristic_events__deleted=False)
Je sais pas si c'est très clair décrit comme ça. Si tu veux on peut en discuter oralement pour être sur que je passe pas )à côté de quelque chose.

2021-06-10 12:08 UTC, LePetitTim commented
Tu n'as pas ajouté de tests :)
Même si ca passe déjà dedans, il faut verifier que ca fonctionne bien ta modification et même dans l'idéal il faudrait faire le test avant la modification. Pour être certain que ta modification ne sert pas a rien.

2021-06-10 12:09 UTC, LePetitTim requested changes
Tu n'as pas ajouté de tests :)
Même si ca passe déjà dedans, il faut verifier que ca fonctionne bien ta modification et même dans l'idéal il faudrait faire le test avant la modification. Pour être certain que ta modification ne sert pas a rien.

2021-06-11 08:00 UTC, Chatewgne commented on geotrek/api/tests/test_v2.py
> +        # No theme should be returned because the is not published anymore
typo "the **trek** is not published"

2021-06-11 08:01 UTC, Chatewgne approved these changes

2021-06-11 12:03 UTC, merged