Implement suricate workflow
GeotrekCE/Geotrek-admin pull request #2731
Opened 2021-08-03 15:15 UTC by Chatewgne

2021-08-09 14:43 UTC, babastienne requested changes

2021-08-09 14:43 UTC, babastienne commented on geotrek/feedback/management/commands/sync_suricate.py
> +            if options["activities_only"] and options["statuses_only"]:
J'ai du mal avec ce cumul de deux arguments "only". Pour moi rien que le nom des arguments (et leur description) me laisse penser qu'il n'est pas vraiment possible de les cumuler.

J'aurai tendance à conseiller de changer le nom des paramètres (en enlevant le "only"). Du coup tu rajoutes un paramètre "alerts" et ensuite tu adaptes tes conditions pour éviter trop de redondance. Du coup tu aurais quelque chose du style :
```
has_no_params = not (options[statuses] | options[activities] | options['alerts'])

if options['activities'] or has_ no_params:
    parser.get_activities()
if options['statuses'] or has_no_params:
    parser.get_statuses()
if options['alerts'] or has_no_params:
    parser.get_alerts(verbosity=verbosity)
```

2021-08-09 14:43 UTC, babastienne commented on geotrek/feedback/models.py
> +    new_status_query = ReportStatus.objects.filter(label="Nouveau")
Pourquoi c'est en Francais ?

2021-08-09 14:43 UTC, babastienne commented on geotrek/feedback/models.py
> +    def try_send_report_managers(self):
Pourquoi ne faire un try catch que maintenant et pas directement dans l'implémentation de `send_report_managers` ?
(Je pose sérieusement la question, est-ce que le choix a été pour une raison justifiée ?)

2021-08-09 14:43 UTC, babastienne commented on geotrek/feedback/models.py
> +    def created_in_suricate_update_display(self):
Je ne suis pas certain de comprendre à quoi sert cette méthode et en quoi elle est différente de celle juste en dessous ?

2021-08-09 14:43 UTC, babastienne commented on geotrek/feedback/views.py
> +class DiveCreate(MapEntityCreate):
Un petit copier/coller depuis l'app Diving ?

2021-08-23 15:54 UTC, numahell reviewed
Nice job ! J'aime bien l'idée du SuricateRequestManager, beaucoup plus clair que les simples méthodes que j'avais faites.

2021-08-23 15:54 UTC, numahell commented on geotrek/feedback/management/commands/sync_suricate.py
> +            "--statuses",
Je l'appellerais `--only-statuses`

2021-08-23 15:54 UTC, numahell commented on geotrek/feedback/management/commands/sync_suricate.py
> +            "--activities",
Je l'appellerais `--only-activities`

2021-08-25 10:39 UTC, Chatewgne commented on geotrek/feedback/templates/feedback/report_email.html
> -{% trans "Link to the report" %} : {{report.full_url}}
Because the report isn't directly saved to base anymore, so it has no url yet and this can't work :/

2021-08-25 10:39 UTC, Chatewgne commented on geotrek/feedback/models.py
> +    suricate_id = models.CharField(
It's a UUID now !

2021-08-25 10:43 UTC, Chatewgne commented on geotrek/feedback/helpers.py
> +class SuricateGestionRequestManager(SuricateRequestManager):
There are two managers, one for each API with (Gestion and Standard), each one holding info for its corresponding API (keys, different methods)

2021-08-25 11:51 UTC, Chatewgne commented on geotrek/feedback/migrations/0013_auto_20210803_1444.py
> +# Generated by Django 3.1.13 on 2021-08-03 14:44
Good point, my mistake, I reverted that

2021-08-25 12:19 UTC, babastienne approved these changes

2021-08-25 12:24 UTC, numahell approved these changes

2021-08-25 12:43 UTC, merged