Depublish signages from PDFs
GeotrekCE/Geotrek-admin pull request #2816
Opened 2021-11-09 15:34 UTC by Chatewgne

2021-11-09 16:37 UTC, babastienne approved these changes

2021-11-16 13:54 UTC, LePetitTim requested changes
Il faut ajouter pour les infrastructures.

2021-11-16 14:04 UTC, Chatewgne commented
> Il faut ajouter pour les infrastructures.

C'est fait !

2021-11-16 14:05 UTC, LePetitTim commented
> > Il faut ajouter pour les infrastructures.
> 
> C'est fait !

C'était surtout pour tracer ma remarque

2021-11-16 14:33 UTC, merged