[#2840] Fix serve attachments, add test url watermark
GeotrekCE/Geotrek-admin pull request #2850
Opened 2021-12-13 17:37 UTC by LePetitTim

2021-12-13 17:41 UTC, camillemonchicourt commented
Cela va aussi changer les URL des médias servis par l'API v2 ?

2021-12-14 08:56 UTC, LePetitTim commented
> 

Non, c'est uniquement pour les medias paperlip. Il y a un fonctionnement qui verifie que tu as les droits sur le media paperclip, si tu n'as pas les droits il ne s'affiche pas.
J'ai juste modifié le fonctionnement pour qu'on puisse servir les images avec des informations ajoutés dessus. (watermark).
Avant, ça devait tomber en marche.

2021-12-14 14:16 UTC, camillemonchicourt commented
OK merci pour les précisions.
Je pensais que le système de watermark n'était utilisé que par les mécanismes de synchronisation (https://github.com/GeotrekCE/Geotrek-admin/issues/1945).
OK donc il est aussi utilisé sur les images servis dans l'API Cirkwi.
Il n'est pas utilisé actuellement dans l'API v2.

Ça serait intéressant de pouvoir l'utiliser dans l'API v2, mais avant cela, je pense qu'il faut revoir la manière dont on l'active ou non, avec un paramètre dédié.
Et ainsi ne pas fournir des noms de fichiers avec ``...watermark...`` quand il n'est pas utilisé.

2021-12-14 14:16 UTC, camillemonchicourt approved these changes

2021-12-14 14:17 UTC, camillemonchicourt commented
Par contre, cette PR utilise une branche dédiée de Mapentity (``classview_serve_attachment``), avant la release dans Geotrek-admin, il faudra basculer sur une release taguée de Mapentity j'imagine.

2021-12-15 08:47 UTC, submarcos commented
> Par contre, cette PR utilise une branche dédiée de Mapentity (`classview_serve_attachment` [makinacorpus/django-mapentity#216](https://github.com/makinacorpus/django-mapentity/pull/216)), avant la release dans Geotrek-admin, il faudra basculer sur une release taguée de Mapentity j'imagine.

oui normalement cette PR aurait du etre ouverte en DRAFT

2021-12-15 18:36 UTC, submarcos requested changes
il manque le changelog

2021-12-15 18:38 UTC, submarcos approved these changes

2021-12-15 21:50 UTC, merged