[#2842] Add new group Editor management and trekking with external ba…
GeotrekCE/Geotrek-admin pull request #2886
Opened 2022-01-06 11:53 UTC by LePetitTim

…ckend

2022-01-06 14:30 UTC, camillemonchicourt approved these changes

2022-01-07 09:19 UTC, submarcos requested changes

2022-01-07 09:19 UTC, submarcos commented on geotrek/authent/fixtures/basic.json
> +        "model": "auth.group",
c'est normal que tu aies changé les pk des fixtures ? au lieu de créer un nouveau groupe tu as changé un groupe existant ?

2022-01-07 09:21 UTC, LePetitTim commented on geotrek/authent/fixtures/basic.json
> +        "model": "auth.group",
Je pense pas que l'on charge les fixtures lorsqu'on a deja une instance mais c'est vrais que c'est mieux

2022-01-07 13:11 UTC, submarcos commented on geotrek/settings/base.py
> +    'EDITOR_TREKKING_MANAGEMENT': 6,
c'est pas 5 du coup ?

2022-01-07 13:42 UTC, merged