[#2845] Add equipments trekking
GeotrekCE/Geotrek-admin pull request #2890
Opened 2022-01-11 10:53 UTC by LePetitTim

2022-01-11 12:59 UTC, LePetitTim commented
Il y a besoin d'un picto pour "materiel" sauf si on ne l'affiche pas dans les pdfs

2022-01-11 13:23 UTC, numahell requested changes
Quelques questions, et les fichiers de traduction s'il y en a des nouveaux, je ferais une autre PR dédiée peut-être.

2022-01-11 13:23 UTC, numahell commented on geotrek/trekking/locale/fr/LC_MESSAGES/django.po
> +
Si ces traductions sont commentées, c'est que les messages ne sont plus présents dans le code

2022-01-11 13:23 UTC, numahell commented on geotrek/trekking/locale/it/LC_MESSAGES/django.po
>  msgstr ""
Je pense que les modifs de ce fichier de traduction dépasse le cadre de la PR

2022-01-11 13:23 UTC, numahell commented on geotrek/trekking/models.py
> +                                 help_text=_("Equipment needed"))
C'est quoi le but de ce champ, ajouter un équipement, ou bien un équipement nécessaire ? si c'est équipement nécessaire, je l'appellerais plutôt `needed_equipment`

2022-01-14 17:06 UTC, LePetitTim commented on geotrek/trekking/locale/it/LC_MESSAGES/django.po
>  msgstr ""
C'est outdated il y avait beaucoup plus de traduction

2022-01-14 17:43 UTC, merged

2022-01-19 08:11 UTC, camillemonchicourt commented
@LePetitTim je ne vois pas l'ajout de ce champs dans la documentation de la customisation des exports, des listes et des formulaires ? Voir https://geotrek.readthedocs.io/en/latest/development.html#model-modification-definition-of-done-for-new-model-fields

2022-04-22 12:53 UTC, camillemonchicourt commented
Il est bien dans la doc avec le nouveau nom "gear"