Add full locales
GeotrekCE/Geotrek-admin pull request #2891
Opened 2022-01-11 16:30 UTC by LePetitTim

.. and use standard django and weblate configuration to translate geotrek !!!

2022-01-11 17:17 UTC, numahell requested changes
Il y a pas mal de message en "fuzzy", il y a une passe à faire.

Tu peux les listes avec la commande `git diff -G"\|" master`

2022-01-11 17:17 UTC, numahell commented on geotrek/trekking/locale/fr/LC_MESSAGES/django.po
> +#~ msgstr "itineraire"
Il y a quelques traductions "fuzzy"

2022-01-12 09:59 UTC, LePetitTim commented on geotrek/trekking/locale/fr/LC_MESSAGES/django.po
> +#~ msgstr "itineraire"
Supprimés

2022-01-12 13:40 UTC, submarcos approved these changes

2022-01-12 13:46 UTC, merged