[#2838] Add level accessibility and tab accessibility
GeotrekCE/Geotrek-admin pull request #2914
Opened 2022-01-19 14:28 UTC by LePetitTim

2022-01-19 15:29 UTC, submarcos commented on geotrek/api/v2/views/trekking.py
> +        return Response(serializer.data)
je ne comprends pas pourquoi tu surcharges le retrieve ici

2022-01-19 15:29 UTC, submarcos commented on geotrek/static/style.css
> +}
à mon avis le selecteur est beaucoup trop général et s'aplliquera toutes les tables stripped. tu dis pouvoir le prefixer avec un classname ou un id un peu plu spécifique

2022-01-19 15:59 UTC, submarcos commented on geotrek/api/v2/views/trekking.py
> +        return Response(serializer.data)
ok vu. çà va necessiter une grosse PR pour rendre çà standard, on fera apres

2022-01-20 13:52 UTC, camillemonchicourt commented
OK le champs a été ajouté dans les exports, dans les filtres ?

Il n'a pas été ajouté dans la doc des champs listables, exportables, masquables. Voir https://geotrek.readthedocs.io/en/latest/development.html#model-modification-definition-of-done-for-new-model-fields

2022-01-20 15:22 UTC, Chatewgne requested changes
Il faut ajouter dans la doc `advanced-configuration.rst` les champs `accessibility_xxxx` dans `HIDDEN_FORM_FIELDS` et `COLUMN_LISTS` (view et export) pour le modèle Trek

2022-01-20 15:23 UTC, Chatewgne commented
> Il faut ajouter dans la doc `advanced-configuration.rst` les champs `accessibility_xxxx` dans `HIDDEN_FORM_FIELDS` et `COLUMN_LISTS` (view et export) pour le modèle Trek

Ah non c'est bon ! my bad

2022-01-21 10:52 UTC, submarcos approved these changes

2022-01-21 12:04 UTC, merged