Add parser informationdesk
GeotrekCE/Geotrek-admin pull request #3134
Opened 2022-06-13 11:40 UTC by LePetitTim

2022-06-13 15:24 UTC, numahell requested changes

2022-06-13 15:24 UTC, numahell commented on geotrek/tourism/parsers.py
> +    def _filter_comm(self, val, code, multiple=True):
Tu peux ajouter un docstring pour expliquer à quoi sert cette méthode ? (en tous cas c'est top d'avoir factorisé ça)

2022-06-13 15:24 UTC, numahell commented on geotrek/tourism/parsers.py
> +class InformationDeskApidaeParser(ApidaeParser):
Un docstring serait pas mal ici aussi (même si le nom est déjà un peu explicite)

2022-06-13 15:48 UTC, LePetitTim commented on geotrek/tourism/parsers.py
> +    def _filter_comm(self, val, code, multiple=True):
Ajouté

2022-06-13 15:48 UTC, LePetitTim commented on geotrek/tourism/parsers.py
> +class InformationDeskApidaeParser(ApidaeParser):
Ajouté

2022-06-13 15:58 UTC, numahell commented on geotrek/tourism/parsers.py
> +        either get all elements separated by a / (multiple=True)
```suggestion
        or get all elements separated by a / (multiple=True)
```

2022-06-13 15:58 UTC, numahell commented on geotrek/tourism/parsers.py
> +        With the code of the section (mail, phone etc...), allow to get the rigth information from 'informations.moyensCommunication'
```suggestion
        With the code of the section (mail, phone etc...), allow to get the right information from 'informations.moyensCommunication'
```

2022-06-14 12:15 UTC, numahell approved these changes

2022-06-14 13:04 UTC, merged