Add alert review
GeotrekCE/Geotrek-admin pull request #3160
Opened 2022-06-23 16:49 UTC by LePetitTim

2022-06-24 12:17 UTC, Chatewgne requested changes

2022-06-24 12:17 UTC, Chatewgne commented on geotrek/common/mixins/models.py
> +        if (old_object and getattr(old_object, 'review', None) != self.review and self.review) and settings.ALERT_REVIEW:
il vaudrait pas mieux vérifier self.review avant de faire la comparaison ?

```
 if (old_object and self.review and getattr(old_object, 'review', None) != self.review) and settings.ALERT_REVIEW:
 ```

2022-06-24 12:17 UTC, Chatewgne commented on geotrek/trekking/tests/test_views.py
> +        element_not_published.published = False
Je l'aurais plutôt mis dans la factory et enlevé cette ligne
```suggestion
        element_not_published = self.modelfactory.create(published=False)
```

2022-06-24 12:18 UTC, Chatewgne commented on geotrek/trekking/tests/test_views.py
> +        element_not_published.published = False
+ ajouter le changelog

2022-06-24 12:54 UTC, LePetitTim commented on geotrek/common/mixins/models.py
> +        if (old_object and getattr(old_object, 'review', None) != self.review and self.review) and settings.ALERT_REVIEW:
Pourquoi ?

2022-07-01 14:03 UTC, submarcos commented on geotrek/common/mixins/models.py
> +        if (old_object and getattr(old_object, 'review', None) != self.review and self.review) and settings.ALERT_REVIEW:
you can't acces review attribute from a queryset, you should get instance from qs

2022-07-05 08:08 UTC, submarcos commented on geotrek/common/mixins/models.py
> +            mail_managers(subject, message, fail_silently=False)
fail_silently=False -> unable to modify review attribute if mail server or configuration has problem

2022-07-05 12:20 UTC, merged