Doc user
GeotrekCE/Geotrek-admin pull request #3183
Opened 2022-07-20 18:47 UTC by babastienne

2022-07-20 21:23 UTC, camillemonchicourt approved these changes

2022-07-21 13:13 UTC, numahell requested changes

2022-07-21 13:13 UTC, numahell commented on docs/usage/configuration-ttw.rst
> +-  Un utilisateur d'une structure pourra tout de même tracer des itinéraires sur des tronçons tracés par une autre structure
```suggestion
- Un utilisateur d'une structure pourra tout de même tracer des itinéraires sur des tronçons tracés par une autre structure
```

2022-07-21 23:48 UTC, babastienne commented on docs/usage/configuration-ttw.rst
> +Il est possible de créer des groupes, et pour chaque groupe d'associer un certain nombre de permissions associées.
Aïe aïe aïe, j'ai pas bien relu, il était trop tard quand j'ai écrit ça ... ^^

2022-07-21 23:49 UTC, babastienne commented on docs/usage/configuration-ttw.rst
> +  que souhaité pour pouvoir refléter de la meilleure manière l'organisation de votre territoire.
```suggestion
Certains groupes existent par défaut dans Geotrek (Geotrek-rando, Lecteurs, Outdoor, Rédacteurs, Référents communication, Référents ronçons, Référents sentiers), mais il est bien entendu possible d'en ajouter d'autres pour refléter l'organisation de votre territoire.
```

2022-07-21 23:52 UTC, babastienne commented on docs/usage/configuration-ttw.rst
> +-  Modification
```suggestion
-  Modification
-  Modification de la géométrie de l'objet
```

2022-07-28 13:19 UTC, numahell reviewed
Tu peux rebaser cette branche pour la CI. Sinon pour le contenu c'est ok pour moi.

2022-07-28 13:20 UTC, numahell approved these changes

2022-07-28 16:17 UTC, merged