add preparation_duration and intervention_duration
GeotrekCE/Geotrek-admin pull request #3281
Opened 2022-10-04 12:19 UTC by TheoLechemia

Add 2 new integer fields : 
- preparation_duration
- intervention_duration
These fields are "private" so I don't add them in API

2022-10-05 08:23 UTC, Chatewgne requested changes

2022-10-05 08:23 UTC, Chatewgne commented on geotrek/tourism/models.py
> +    intervention_duration = models.IntegerField(verbose_name=_("Intervention duration"), blank=True, null=True)
If this is meant to be in Hours I think we should copy this field : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/models.py#L135
with FloatField, validator and help_text

2022-10-05 08:23 UTC, Chatewgne commented on docs/install/advanced-configuration.rst
> +            'intervention_duration'
Please update `docs/changelog.rst` with these new fields

2022-10-11 08:02 UTC, Chatewgne commented on geotrek/tourism/models.py
> +    _("Published touristic events"),
Please undo whole file formatting

2022-10-11 09:02 UTC, camillemonchicourt commented
@TheoLechemia, il faut aussi faire pointer cette PR vers la branche "master".

2022-10-11 11:59 UTC, TheoLechemia commented on geotrek/tourism/models.py
> +    _("Published touristic events"),
DOne

2022-10-11 12:06 UTC, TheoLechemia commented
Do I have to modify the PDF ?

2022-10-11 13:27 UTC, Chatewgne commented
> Do I have to modify the PDF ?

I don't think so, @camillemonchicourt ?

2022-10-11 13:39 UTC, camillemonchicourt commented
Not it shouldn't be in the public PDF, as these are private fields that we don't put in API v2, nor Geotrek-rando, nor the PDF.

2022-10-18 12:41 UTC, marcantoinedupre approved these changes
It looks good! :+1:

2022-10-19 12:15 UTC, merged