Improve APIDAE Trek parser output with entities external IDs
GeotrekCE/Geotrek-admin pull request #3429
Opened 2023-01-25 13:01 UTC by marcantoinedupre

La rapport d'import ressemble maintenant à :

> 
> 71/71 lignes importées.
> 64 enregistrements mis à jour.
> 5 enregistrements non modifiés.
> 2 avertissements :
> 
>     # APIDAE Trek #320507 at line 19:
>     - Le champ required 'multimedias' est manquant,
>     # APIDAE Trek #4787235 at line 44:
>     - The trek from APIDAE has no attachment with the type "PLAN",

Précedemment seul le numéro de ligne durant l'import était visible.

2023-01-30 13:07 UTC, submarcos approved these changes

2023-01-30 13:11 UTC, numahell requested changes
Nice PR, just need translation maybe

2023-01-30 13:11 UTC, numahell commented on geotrek/trekking/parsers.py
> +        key = f"APIDAE Trek #{self.eid_val} at line {self.line}"
This line may be added to translations

2023-01-30 15:13 UTC, Chatewgne approved these changes

2023-01-31 13:55 UTC, marcantoinedupre commented on geotrek/trekking/parsers.py
> +        key = f"APIDAE Trek #{self.eid_val} at line {self.line}"
Yes, done.

2023-01-31 13:56 UTC, merged