:sparkles: Add linepictogram menu for each lines [#3327]
GeotrekCE/Geotrek-admin pull request #3448
Opened 2023-01-27 15:55 UTC by LePetitTim

2023-08-07 12:42 UTC, Chatewgne requested changes

2023-08-08 08:02 UTC, Huquette commented
Bonjour, je suis actuellement en train de faire les traductions d'anglais à français et je voulais savoir comment est-ce que tu souhaiterais que "Line pictograms" soit traduit, j'ai pensé à "Pictogrammes des lignes" mais je ne suis pas sûr. @camillemonchicourt

2023-08-08 13:10 UTC, Huquette commented
> Bonjour, je suis actuellement en train de faire les traductions d'anglais à français et je voulais savoir comment est-ce que tu souhaiterais que "Line pictograms" soit traduit, j'ai pensé à "Pictogrammes des lignes" mais je ne suis pas sûr. @camillemonchicourt

Aussi, est-ce qu'on prévoit des champs traduisibles pour label et description de LinePictogram ?

2023-08-09 06:49 UTC, camillemonchicourt commented on geotrek/signage/fixtures/pictograms.json
> +            "date_update": "2014-02-12T11:21:48.961Z",
Pourquoi dans les nouvelles fixtures, on ne met pas plutôt la date où les a ajouté dans Geotrek-admin (2023-08...) ?

2023-08-09 06:57 UTC, camillemonchicourt commented on docs/install/advanced-configuration.rst
> +If you want to add default pictograms of national parks and french departments, you can execute this command:
Actuellement la fixture n'inclut que les pictogrammes spécifiques des parcs nationaux, pas ceux des départements.

2023-08-11 08:11 UTC, Chatewgne commented on geotrek/signage/locale/fr/LC_MESSAGES/django.po
> +msgstr "Pictogramme"
Should be plural or singular in both languages

2023-08-14 10:30 UTC, marcantoinedupre commented
J'ai une erreur durant la migration :

```
Read env configuration from /opt/geotrek-admin/geotrek/settings/env_dev.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Operations to perform:
  Apply all migrations: admin, altimetry, auth, authent, cirkwi, common, contenttypes, core, diving, django_celery_results, easy_thumbnails, feedback, flatpages, infrastructure, land, maintenance, mapentity, outdoor, sensitivity, sessions, signage, tourism, trekking, zoning
Running migrations:
  Applying signage.0028_auto_20230126_1309... OK
  Applying signage.0029_migrate_pictogram...Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
__fake__.DoesNotExist: LinePictogram matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "label" violates not-null constraint
DETAIL:  Failing row contains (1, 2023-08-14 10:13:44.599809+00, 2023-08-14 10:13:44.59982+00, , null, , , null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/geotrek/common/management/commands/migrate.py", line 14, in handle
    super().handle(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/geotrek-admin/geotrek/signage/migrations/0029_migrate_pictogram.py", line 8, in migrate_pictogram
    line_pictogram, created = LinePictogram.objects.get_or_create(label=line.pictogram_name)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "label" violates not-null constraint
DETAIL:  Failing row contains (1, 2023-08-14 10:13:44.599809+00, 2023-08-14 10:13:44.59982+00, , null, , , null).
```

Je pense qu'il faut gérer le cas où le champ `Line.pictogram_name` est null [dans la migration](https://github.com/GeotrekCE/Geotrek-admin/pull/3448/files#diff-04bafb501c286fa5812c4760115119113ab4304444f2f6a9c9d2fb36f8a225bfR8) :

```
    for line in Line.objects.all():
        line_pictogram, created = LinePictogram.objects.get_or_create(label=line.pictogram_name)
```
Avec `for line in Line.objects.exclude(pictogram_name=None)` ?

2023-08-25 11:08 UTC, Chatewgne approved these changes

2023-08-28 08:00 UTC, merged