✨ Add link with information desks
GeotrekCE/Geotrek-admin pull request #3623
Opened 2023-06-26 14:13 UTC by LePetitTim

2023-06-30 14:30 UTC, marcantoinedupre requested changes
Cool :+1: je t'ai fait quelques remarques.

2023-06-30 14:30 UTC, marcantoinedupre commented on geotrek/common/tests/test_parsers.py
> +        # Then inside start_meta()
À supprimer ? Je ne sais pas si c'est exact, normalement il y a 2 `end_meta`, non ?

2023-06-30 14:30 UTC, marcantoinedupre commented on geotrek/tourism/parsers.py
> +        self.root = response.json()
Pareil ici, c'est plutôt confusant de réutiliser `self.root` et `self.items` pour parser des Treks avec le parser `GeotrekInformationDeskParser`. Pourquoi ne pas juste passer la data de la réponse à `link_informationdesks` et itérer dessus ?

2023-07-03 08:01 UTC, LePetitTim commented on geotrek/common/tests/test_parsers.py
> +        # Then inside start_meta()
Je fais 2 fois la commande import

2023-07-03 12:43 UTC, marcantoinedupre approved these changes
Yes :sparkles:  :+1:

2023-07-03 12:46 UTC, merged