Add a manager filter to the blades
GeotrekCE/Geotrek-admin pull request #3629
Opened 2023-07-06 08:46 UTC by Huquette

A user can now filter the blades by manager (organism).

2023-07-06 08:59 UTC, Chatewgne requested changes
Please add an entry to changelog : in file `docs/changelog.rst` add a line describing your feature under "new feature" for next version (2.98.1+dev)

2023-07-06 09:55 UTC, babastienne commented
Description du dev :  

L'idée est d'ajouter la possibilité de filtrer les lames des signalétique pour n'afficher que celles associées à un gestionnaire. Les lames n'ont pas de gestionnaires mais sont rattachées à des signalétiques qui ont un gestionnaire, et donc c'est de là que provient l'information.

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/9b68d122-e2e9-4aff-81ff-730d11704ebe)

Origine du besoin : https://github.com/GeotrekCE/Geotrek-admin/issues/2837#issuecomment-1479827869

2023-07-10 12:28 UTC, marcantoinedupre commented
:clap:

2023-07-10 12:44 UTC, Chatewgne approved these changes

2023-07-10 14:12 UTC, merged