corrections français et url non valides
GeotrekCE/Geotrek-admin pull request #3638
Opened 2023-07-13 10:42 UTC by bruhnild

2023-07-17 11:48 UTC, babastienne requested changes

2023-07-17 11:48 UTC, babastienne commented on docs/usage/management-modules.rst
> +Il peuvent être numérisés dans Geotrek-admin, mais il est conseillé de les importer, directement en SQL dans la base de données ou depuis QGIS (https://makina-corpus.com/sig-webmapping/importer-une-c
Ca peut être intéressant de parler ici de la commande permettant d'importer les tronçons qui est aussi disponible dans Geotrek. Cette commande est détaillée plus loin dans la documentation : https://geotrek.readthedocs.io/en/2.98.1/install/import.html#import-paths

J'aurai même tendance à dire que c'est la procédure privilégiée encore plus que de passer par QGis ou du SQL qui peut parfois être problématique si les données sont mal pré-traitées, la commande ayant l'avantage de faire des vérifications sur les données avant insertion dans la base.

2023-07-17 11:48 UTC, babastienne commented on docs/usage/static-pages.rst
> +L'interface permet de construire sa page en responsive design, c'est-à-dire qu'il est possible de disposer les blocs de contenu pour s'adapter aux différentes tailles d'écrans des utilisateurs.
Toute la section de la doc liée à la mise en page des pages statiques n'est plus à jour. Depuis Geotrek-Rando V3 Bootstrap n'est plus utilisé, ce qui signifie que la mise en page créée dans Geotrek-Admin n'est en réalité pas reproduite sur le site public. 

Concrètement ce qu'il faudrait faire : retirer la fonctionnalité de mise en page de Geotrek-Admin car elle induit en erreur les utilisateurs, revoir la documentation pour alerter les utilisateurs qu'il s'agit d'une feature obsolète (Geotrek-rando V2) ou alors carrément retirer cette section et expliquer comment est géré la mise en page actuelle dans Geotrek-Rando V3 (via des exemples et des captures d'écrans ?).

Infos complémentaires : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/466

2023-07-19 06:50 UTC, bruhnild commented on docs/usage/management-modules.rst
> +Il peuvent être numérisés dans Geotrek-admin, mais il est conseillé de les importer, directement en SQL dans la base de données ou depuis QGIS (https://makina-corpus.com/sig-webmapping/importer-une-c
Néanmoins, depuis la version 2.20 de Geotrek-admin (voir le changelog : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.20.0)

2023-07-19 06:50 UTC, bruhnild commented on docs/usage/management-modules.rst
> +En termes de structuration, le choix initial a été de concevoir, sur le volet gestion, la gestion des valeurs des listes déroulantes structure par structure pour que chaque structure travaillant sur
Néanmoins, depuis la version 2.20 de Geotrek-admin (voir le changelog : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.20.0)

2023-07-19 07:13 UTC, bruhnild commented on docs/usage/static-pages.rst
> +L'interface permet de construire sa page en responsive design, c'est-à-dire qu'il est possible de disposer les blocs de contenu pour s'adapter aux différentes tailles d'écrans des utilisateurs.
En attendant de rédiger la documentation sur le fonctionnement actuel (rando v3), je propose de mettre un encart d'alerte :  

.. danger::
    Depuis Geotrek-Rando V3, le composant Bootstrap n'est plus utilisé pour gérer les différentes tailles d'écran. Cela signifie que la mise en page créée dans Geotrek-Admin n'est pas reproduite sur le site public. Cette documentation n'est valable que pour Geotrek-Rando V2 en attendant sa mise à jour expliquant le fonctionnement actuel.

2023-07-19 09:23 UTC, babastienne commented on docs/usage/management-modules.rst
> +En termes de structuration, le choix initial a été de concevoir, sur le volet gestion, la gestion des valeurs des listes déroulantes structure par structure pour que chaque structure travaillant sur
Oui ok pour cette formulation

2023-07-19 09:24 UTC, babastienne commented on docs/usage/management-modules.rst
> +Il peuvent être numérisés dans Geotrek-admin, mais il est conseillé de les importer, directement en SQL dans la base de données ou depuis QGIS (https://makina-corpus.com/sig-webmapping/importer-une-c
Ok très bien

2023-07-19 09:24 UTC, babastienne commented on docs/usage/static-pages.rst
> +L'interface permet de construire sa page en responsive design, c'est-à-dire qu'il est possible de disposer les blocs de contenu pour s'adapter aux différentes tailles d'écrans des utilisateurs.
Oui pourquoi pas. Et rajoute aussi un lien vers le ticket Geotrek-Rando V3 correspondant.

2023-07-24 08:17 UTC, numahell approved these changes

2023-07-24 09:35 UTC, babastienne approved these changes

2023-07-24 09:39 UTC, merged