Add a multiselect to filter the Blades by more than one manager
GeotrekCE/Geotrek-admin pull request #3644
Opened 2023-07-19 09:17 UTC by Huquette

2023-07-20 21:32 UTC, camillemonchicourt commented
Est-ce fait globalement pour tous les filtres ?
Car il n'y a pas de raison que cela soit le cas pour ce filtre des gestionnaires de signalétique, alors qu'il a le même statut que les autres filtres.
Et cela serait une évolution utile pour tous les filtres.

2023-07-21 12:16 UTC, Huquette commented
> Est-ce fait globalement pour tous les filtres ? Car il n'y a pas de raison que cela soit le cas pour ce filtre des gestionnaires de signalétique, alors qu'il a le même statut que les autres filtres. Et cela serait une évolution utile pour tous les filtres.

C'est déjà le cas pour les autres filtres, c'est justement pour homogénéiser le tout que le multiselect ici est convenable :)

2023-07-21 12:43 UTC, marcantoinedupre commented on geotrek/signage/models.py
> +    def manager(self):
Cette `property` n'est p-ê pas nécessaire ? Tu ne l'utilises que dans les tests il me semble. Je pense que c'est pertinent de garder le passage par `signage` explicite dans les filtres/tests.

2023-07-21 13:46 UTC, Huquette commented on geotrek/signage/models.py
> +    def manager(self):
Oui tout à fait, je viens de l'enlever, merci :)

2023-07-25 12:34 UTC, Chatewgne requested changes

2023-07-25 12:34 UTC, Chatewgne commented on geotrek/signage/tests/test_models.py
> +        self.assertEqual(self.blade.signage.manager, self.signage.manager)
This test is not necessary

2023-07-25 12:34 UTC, Chatewgne commented on geotrek/signage/filters.py
> +                                        help_text=_("Filter by one or more manager."))
is this helptext translated ?

2023-07-25 12:34 UTC, Chatewgne commented on geotrek/signage/tests/test_views.py
> +            f'option value="{self.manager.pk}">{self.manager.organism}</option>'
You should test that the signage is in the response (ant that signage2 is not), not the selectors for the filters

2023-08-02 08:01 UTC, Chatewgne requested changes

2023-08-02 08:01 UTC, Chatewgne commented on docs/changelog.rst
> +**Improvements**
Label publication is a new feature, you shouldn't change the title here
```suggestion

**New features**

- Filter trek and outdoor site labels according to whether they are published or not (#3529)

**Improvements**

- Add a multiselect to filter the Blades by more than one manager
- Filter by multiple structures on Blades list (#3646)

```

2023-08-08 07:50 UTC, Chatewgne approved these changes

2023-08-09 09:29 UTC, merged