Add command to identify and merge some paths
GeotrekCE/Geotrek-admin pull request #3648
Opened 2023-07-21 15:42 UTC by Chatewgne

2023-07-23 16:20 UTC, babastienne commented on geotrek/core/tests/test_commands.py
> +        #                +
Can't we achieve the following result with the this command ?

```python
#  After x call :
#        p1                         p3              
# +--------------+-------------------------------------------+
#                |
#                |  p4
#                |
#                +
```

2023-07-24 08:14 UTC, babastienne commented on geotrek/core/tests/test_commands.py
> +        #                +
It works in the web interface of Geotrek-Admin, that's why I was asking. Isn't the same function called behind ?

2023-07-25 16:05 UTC, babastienne commented
:pray: :heart:

2023-07-26 19:54 UTC, babastienne requested changes
Can you add some explanations in the[ "exploitation command" section of the documentation](https://geotrek.readthedocs.io/en/2.99.0/install/import.html#exploitation-commands) please ?

2023-07-27 11:12 UTC, babastienne commented
> > Can you add some explanations in the[ "exploitation command" section of the documentation](https://geotrek.readthedocs.io/en/2.99.0/install/import.html#exploitation-commands) please ?
> 
> ![image](https://user-images.githubusercontent.com/26015573/256504299-c4b070c9-c42c-4d60-99fc-8c56c08dae98.png)

Great, thanks @Chatewgne. Could you put the warning in a "danger" section in order for it to but more visible ? Like this : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/706d5b8c-90e5-4394-a2d8-24a908f2ae42)

2023-07-27 11:56 UTC, Chatewgne commented
> Great, thanks @Chatewgne. Could you put the warning in a "danger" section in order for it to but more visible ? Like this 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/26015573/9554609e-f8b1-407f-9104-ed280d7603ed)

2023-09-05 16:42 UTC, babastienne approved these changes
Looks good to me.

Already used on multiple instances and it works fine !

2024-01-11 12:55 UTC, babastienne commented
I used this command already and recently again on two instances without identifying any issue. Could this PR be merged soon ?

2024-01-11 12:59 UTC, Chatewgne commented
> I used this command already and recently again on two instances without identifying any issue. Could this PR be merged soon or is it missing something ?

Glad to hear it worked fine, I'll rebase and merge it :hugs:

2024-01-11 13:19 UTC, merged