For tourism events, filter by begin date by default
GeotrekCE/Geotrek-admin pull request #3650
Opened 2023-07-25 12:57 UTC by Huquette

For more details: https://github.com/GeotrekCE/Geotrek-admin/issues/3597

2023-08-02 08:11 UTC, Chatewgne requested changes

2023-08-02 08:11 UTC, Chatewgne commented on docs/changelog.rst
> +- Filter by begin date by default on touristic events (#3597)
Please specify "in APIv2", and it should be in block "Improvements" as well

2023-08-03 16:32 UTC, camillemonchicourt commented
Comme j'indiquai dans le ticket (https://github.com/GeotrekCE/Geotrek-admin/issues/3597#issuecomment-1551240699), pour les événements on les trie plutôt par défaut par date de fin, car sinon les événements longs (comme les expositions qui durent plusieurs mois et dont la date de début est souvent passée si l'expo est en cours) arrivent toujours en haut de la liste, à la place des événements du jour ou du lendemain.

2023-08-03 16:45 UTC, babastienne commented
Oui en effet bien vu, merci pour ta vigilance @camillemonchicourt

2023-08-03 16:46 UTC, babastienne requested changes

2023-08-03 16:46 UTC, babastienne commented on geotrek/api/v2/views/tourism.py
> +            .order_by('begin_date')  # Required for reliable pagination
```suggestion
            .order_by('end_date')  # Required for reliable pagination
```

2023-08-03 17:18 UTC, camillemonchicourt commented
Attention à un point cependant.
A la saisie, seule la date de début est obligatoire.
Donc tous les événements qui sont sur une seule journée peuvent avoir une date_fin nulle.

Dans l'API on fait en sorte de renvoyer date_fin=date_debut si date_fin n'est pas rempli, mais si on trie par défaut les événements par date_fin, il faut faire la même chose au préalable, au risque d'avoir plein d'événement sans date_fin.

2023-08-07 12:38 UTC, Chatewgne approved these changes

2023-08-09 12:28 UTC, merged