ajout information creation etiquette
GeotrekCE/Geotrek-admin pull request #3662
Opened 2023-08-17 15:07 UTC by bruhnild

2023-08-17 16:03 UTC, camillemonchicourt approved these changes

2023-08-23 07:00 UTC, Chatewgne approved these changes

2023-08-23 07:58 UTC, babastienne requested changes
Je me demande si en plus on ne peut pas mettre quelques lignes pour montrer à quoi ressemble les étiquettes dans Geotrek-Rando ? Pour que ce soit plus parlant ?

Également on peut montrer comment associer une étiquette à un contenu dans Geotrek-Admin ?

2023-08-23 07:58 UTC, babastienne commented on docs/usage/configuration-ttw.rst
> +Pour mettre en forme le contenu de l'étiquette, il est possible d'utiliser du HTML. Pour cela, il est recommandé d'utiliser des outils permettant de formater du contenu et d'obtenir le résultat en HT
Il y a une limite de contenu sur le site mis en lien. De plus ce n'est pas libre donc pas top. On pourrait mettre en avant plutôt un outil libre ? Quitte à rester dans la continuité de l’environnement de Geotrek on pourrait proposer d'utiliser TinyMCE : https://www.tiny.cloud/docs/demo/basic-example/

2023-08-23 07:58 UTC, babastienne commented on docs/usage/configuration-ttw.rst
> +.. image :: ../images/admin/creation_etiquette.png
Peux-tu modifier l'image pour en inclure une sans faute d'orthographe et avec un lien d'image générique pointant vers http://example.org/image.jpg plutôt que sur une instance précise ?

2023-08-24 07:52 UTC, babastienne approved these changes

2023-08-24 07:55 UTC, merged