Docs reorg settings refsettings in advanced
GeotrekCE/Geotrek-admin pull request #3722
Opened 2023-09-11 18:57 UTC by numahell

Reorganize settings sections

## Description

- reorganize advanced settings with fewer sections but more visible sub-sections : https://geotrek.readthedocs.io/en/docs-reorg-settings/install/advanced-configuration.html
- move settings details to settings reference : https://geotrek.readthedocs.io/en/docs-reorg-settings/install/settings-reference.html

## Related Issue

Discussion started on this PR #3669

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/CONTRIBUTING.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation]()https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields
- [ ] I have performed a self-review of my code
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works.~~
- [ ] ~~New and existing unit tests pass locally with my changes~~
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2023-09-12 16:41 UTC, babastienne approved these changes

2023-09-12 16:43 UTC, babastienne requested changes
For your commits try to squash them all in order to reduce the number of commits. also you can mention related issue in the commit message. If you add "fix #3669" in your commit message the issue will automatically be closed when merging the pull request. If you don't want the issue to be automatically closed you can just add "ref #3669" to reference the issue.

2023-09-12 16:43 UTC, babastienne commented on docs/changelog.rst
> +- Reorganize settings section (related to PR #3669)
```suggestion
- Reorganize settings section (related to issue #3669)
```

2023-09-14 08:21 UTC, numahell commented on docs/changelog.rst
> +- Reorganize settings section (related to PR #3669)
Oui mais c'est en fait une PR, même si c'est le brouillon de celle-ci et qu'elle ne sera jamain mergée je voulais être précise.

2023-09-14 09:31 UTC, babastienne commented on docs/changelog.rst
> +- Reorganize settings section (related to PR #3669)
Ah ok my bad :laughing:

2023-09-14 18:28 UTC, babastienne approved these changes

2023-09-18 13:23 UTC, merged