Hot fix provider_choices
GeotrekCE/Geotrek-admin pull request #3810
Opened 2023-10-25 16:00 UTC by juggler31

## Description

Update provider choice call with tests

## Related Issue

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/CONTRIBUTING.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation]()https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2023-10-25 19:13 UTC, babastienne commented on geotrek/signage/tests/test_views.py
> +from geotrek.signage.views import SignageList
```suggestion
```

2023-10-26 07:30 UTC, submarcos commented on geotrek/signage/managers.py
> +    #     return providers
delete this comment part

2023-10-26 07:31 UTC, submarcos reviewed
comments to delete

2023-10-26 07:42 UTC, Chatewgne requested changes

2023-10-26 07:42 UTC, Chatewgne commented on geotrek/trekking/tests/test_views.py
> +        signage2 = ServiceFactory.create(provider='my_provider2')
Should be `service1` and `service2`

2023-10-26 07:42 UTC, Chatewgne commented on geotrek/trekking/tests/test_views.py
> +        signage2 = POIFactory.create(provider='my_provider2')
Should be `poi1` and `poi2`

2023-10-26 08:51 UTC, submarcos approved these changes

2023-10-26 09:17 UTC, merged