update doc
GeotrekCE/Geotrek-admin pull request #3890
Opened 2024-01-17 14:39 UTC by bruhnild

## Description

## Related Issue

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/CONTRIBUTING.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation](https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2024-01-18 11:42 UTC, camillemonchicourt requested changes

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/editing-objects.rst
> +La **segmentation dynamique** consiste en un ensemble de déclencheurs calculant automatiquement les géométries résultantes à la création et lors de modifications sur le réseau de tronçons. Cela perme
Je dirai plutôt : 
"La **segmentation dynamique** permet de saisir et stocker des informations relatives aux tronçons. Elle s'accompagne d'un ensemble de déclencheurs calculant automatiquement les géométries résultantes à la création et lors de modifications sur le réseau de tronçons. Cela permet de garantir une cohérence géométrique et topologique entre les tronçons et les objets liés (travaux, aménagements, statuts, itinéraires...), mais aussi d'associer tous les objets entre eux en vérifiant leur superposition sur le réseau."

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +    • Décathlon Outdoor
Whympr, UtagawaVTT et Decathlon Outdoor n'ont pas encore de passerelle opérationnelle branchée à l'API de Geotrek.
Par contre c'est le cas de Apidae, IGNrando' et Outdooractive

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +    • VisoRando
Visorando

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +	Au survol d'un objet sur la carte, celui-ci est mis en évidence dans la liste.
Ce n'est malheuresement plus le cas depuis la mise en place de la pagination serveur des listes (https://github.com/GeotrekCE/Geotrek-admin/issues/3110)

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Description : Itinéraire publié ou en boruillon
brouillon

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Exemple : Il s’agit de la difficulté technique et motrice (présence et taille d’obstacles).
C'est plutôt une description pour préciser la valeur de la cotation, pas son type.
Exemple : "La technicité de cet itinéraire est moyenne car elle ne comprend pas de passages délicats"

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Description : liens web approtant des compléments d'informations utiles
apportant

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Exemple : Pente supérieure à 12%12%
12%

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Description : description de la pente : supérieure à 10 % (Nécessite une assistance quand la pente est supérieur à 8%)
est supérieure à 8%

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Exemple : Sentier étroit demandant une forte technique de conduite
Sentier étroit demandant une forte technique de conduite, avec un passage d'un mètre de large

2024-01-18 11:42 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- Exemple : Passage resserré sur le pont traversant la rivière.
Ça on le mettrait plutôt dans le champs LARGEUR.
Un exemple serait plutôt : "La montée du Saut du Laire, particulièrement les 150 derniers mètres, sont déconseillés aux joëlettes, notamment dans la perspective du retour en descente sur pavé pouvant être glissant"

2024-01-19 16:53 UTC, babastienne commented
Est-ce possible de fusionner un peu les commits ? 42 commits pour une PR de doc ça me parait assez élevé.

2024-01-19 16:58 UTC, bruhnild commented
> Est-ce possible de fusionner un peu les commits ? 42 commits pour une PR de doc ça me parait assez élevé.

Je pourrais les fusionner au moment du merge de la PR

2024-01-23 20:26 UTC, babastienne commented
Review rapide : 
- Page d'accueil
    - Section "Les 4 briques" : possible de rajouter un lien sur chaque brique vers la documentation dédiée ?
- Section "Présentation générale" : [ça j'adore](https://geotrek.readthedocs.io/en/mfu-improve-doc/usage/overview.html#interface-de-consultation-des-modules) :heart_eyes: C'est très chouette. Peut-être à faire relire par @camillemonchicourt ?
- Section "Modules de valorisation" : 
    - il manque pas mal d'infos sur certains modules.
    - Pour es sections "Outdoor" il y a une erreur, il y est évoqué le module Zones sensibles qui n'a rien à voir
    - Pourquoi ne pas y mettre directement toute la section "Activités Outdoor" dedans ?
    - Section "Activité outdoor" : les images HD ne sont pas relatives qu'aux activités outdoor, c'est aussi possible sur les itinéraires. Peut-être en faire une section dédiée plutôt que de l'inclure dans l'outdoor ?
- A suivre ...

2024-01-23 22:56 UTC, camillemonchicourt reviewed
Merci pour ces ajouts très utiles.
J'ai fait une relecture complète et de nombreuses suggestions d'ajustements, ainsi que quelques commentaires.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/about/geotrek.rst
> +* des fonctionnalités de gestion des informations (itinéraires, destinations, points d’intérêts, description, interprétation…) et de gestion des infrastructures (signalétique, aménagement, travaux, r
```suggestion
* des fonctionnalités de gestion des informations (itinéraires, sites outdoor, points d’intérêts, description, interprétation, médias…) et de gestion des infrastructures (signalétique, aménagements, travaux, réglementation…) pour les utilisateurs gérant un territoire (**Geotrek-admin**) 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/about/geotrek.rst
> +* des fonctionnalités simples et ludiques de recherche et de parcours d’itinéraires pour les internautes et les mobinautes (**Geotrek-Rando V3**, **Geotrek-Mobile** et **Geotrek-Widget**).
```suggestion
* des fonctionnalités simples et ludiques de recherche et de consultation d’itinéraires pour les internautes et les mobinautes (**Geotrek-rando V3**, **Geotrek-mobile** et **Geotrek-rando-widget**).
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/editing-objects.rst
> +L'édition des objets s'effectue en 2D, et leur géométrie est “drapée” automatiquement en 3D sur un Modèle Numérique de Terrain stocké en base au format raster.
```suggestion
L'édition des objets s'effectue en 2D, et leur géométrie est “drapée” automatiquement en 3D sur un Modèle Numérique de Terrain stocké dans la base de données au format raster.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/editing-objects.rst
> +Cette information est visible à travers le profil altimétrique pour les tronçons et les itinéraires.
```suggestion
Cette information est visible à travers le profil altimétrique pour les tronçons, les itinéraires et les autres objets linéaires.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/editing-objects.rst
> +Pour importer automatiquement des éléments de POIs, se référer à la section :ref:`Import DEM (altimetry) <import-dem-altimetry>`
Je comprends pas le lien entre les imports de POI et l'import du MNT ?

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +Geotrek dispose d’une API (Application Programming Interface) qui sert à exposer les informations de Geotrek-Admin dans le but de pouvoir faire communiquer des systèmes entre eux pour échanger des do
```suggestion
Geotrek dispose d’une API (Application Programming Interface) qui sert à exposer les données stockées dans une instance de Geotrek-admin, dans le but de pouvoir la faire communiquer avec d'autres outils, systèmes et plateforme et ainsi échanger des données.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +7.1 API interne
Je ne parlerai pas d'API interne, justement car elle a pour vocation uniquement d'échanger avec l'externe.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +   Ensemble des champs paramétrables pour le référentiel CIKWI
```suggestion
   Ensemble des champs paramétrables pour le référentiel CIRKWI
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +Actuellement, certains contenus touristiques sont synchronisés automatiquement avec une base APIDAE, il s'agit des contenus situés dans les catégories suivantes :
```suggestion
Actuellement, certains contenus touristiques peuvent être synchronisés automatiquement avec une base APIDAE. Il s'agit des contenus situés dans les catégories suivantes :
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +- Point info
Ce ne sont pas que ceux-là, et pas vraiment les points d'infos.

Je dirai plutôt : 
- Contenus touristiques (hébergements, restaurants, produits du territoire, lieux de visites...)
- Evénements touristiques (expositions, conférences, sorties...)

Il existe aussi une passerelle Apidae vers Geotrek permettant d'importer des randos d'Apidae vers Geotrek.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +Les autres contenus touristiques sont synchronisés avec un flux Esprit Parc National et sont situés dans une catégorie du même nom.
```suggestion
Les contenus touristiques peuvent aussi être synchronisés depuis des flux Tourinsoft ou Esprit Parc National.
```

Cela dépend de chaque structure, chaque territoire et est très variable. 
Il y a aussi des Geotrek où rien de tout ça n'est importé, mais saisi directement dans Geotrek-admin.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +Il est également possible de mettre en place une passerelle pour les POIs, les Lieux de Renseignement, les Aménagements. Il est aussi possible d'enrichir le lien avec les contenus touristiques pour a
```suggestion
Il est également possible de mettre en place des passerelles pour importer les POIs, les Lieux de Renseignement, les Aménagements. Il est aussi possible d'enrichir le lien avec les contenus touristiques pour avoir par exemple d'autres catégories.
```

Je ne comprends pas la dernière phrase "Il est aussi possible d'enrichir le lien avec les contenus touristiques pour avoir par exemple d'autres catégories."

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +Il existe aussi un lien dans l'autre sens, permettant d'envoyer vers APDIAE les itinéraires pédestres existants dans Geotrek.
```suggestion
Il existe aussi un lien dans l'autre sens, permettant d'importer automatiquement vers APDIAE les itinéraires existants dans une instance Geotrek.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +L'API permet de connecter une instance Geotrek vers les "Équipements" contenant le critère "itinéraire de randonnée pédestre" dans APIDAE.
```suggestion
L'API permet de connecter une instance Geotrek pour importer des itinéraires vers les objets de type "Équipements" dans APIDAE.
```

Cela n'alimente pas que des itinéraires "itinéraire de randonnée pédestre", mais aussi du VTT, du trail, équestre, etc...

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/externals-apis.rst
> +Les randonnées VTT, trail, vélo et les tours itinérants ne sont pas intégrés à ce jour dans la passerelle
Si ils le sont.
```suggestion
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/management-modules.rst
> +C'est le socle essentiel et central de Geotrek. Un tronçon est un objet linéaire, entre 2 intersections. Le mécanisme de ségmentation dynamique permet de ne pas devoir le recouper pour y rattacher de
```suggestion
C'est le socle essentiel et central de Geotrek. Un tronçon est un objet linéaire, entre 2 intersections. Le mécanisme de segmentation dynamique permet de ne pas devoir le recouper pour y rattacher des informations.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +* d’une **page d’accueil**, demandant la saisie d’un login et d’un mot de passe 
```suggestion
* d’une **page d'authentification**, demandant la saisie d’un login et d’un mot de passe 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +* d’une **interface de consultation des modules** 
```suggestion
* d’une **interface de consultation des objets de chaque module** 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +1.2 Page d'accueil
```suggestion
1.2 Page d'authentification
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | C'est l’équivalent du réseau routier : ils constituent le support des tracés
```suggestion
     - | C'est l’équivalent du réseau routier : ils constituent le support des tracés des objets linéaires (itinéraires, statuts, interventions, aménagements...)
```
Pas seulement les itinéraires.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Gestion des communes, organismes ayant la compétence sentiers,
Enlever "communes, zones protégées et secteurs" qui ne sont pas gérés dans le module STATUTS.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Répertorie les travaux liés à l'entretien courant des ouvrages.
Pas que l'entretien courant des ouvrages.
Mais aussi l'entretien sur les sentiers, la mise en place et l'entretien de la signalétique, etc...

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Correspond aux exemples d'interventions. Cela permet d'avoir une
```suggestion
     - | Correspond à des ensembles d'interventions. Cela permet d'avoir une 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Tracés présentés au grand public : l’itinéraire est défini selon
```suggestion
     - | Randonnées présentés au grand public : l’itinéraire est défini selon 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +       | ou la dé-publication sont fréquents
La dé-publication est fortement déconseillée pour le référencement et les passerelles avec d'autres outils.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Ponctuels associés aux randonnées : en fonction de leur
```suggestion
     - | Ponctuels à découvrir associés aux randonnées : en fonction de leur 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +       | Type physique (route, piste, sente, etc.)
Le "Type physique" n'est pas géré dans le module Services, mais dans le module Statuts. A ne pas mentionner ici.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Correspond aux informations issues des Systèmes d'Informations
Non, les contenus touristiques ne viennent pas forcément de SIT, certains les saisissent directement dans Geotrek-admin
```suggestion
     - | Correspond aux services touristiques pouvant être importés depuis des Systèmes d'Informations 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +       | catégories de type : dormir pour les campings, gîtes… ou manger
Par défaut, on n'a pas des catégories nommées "Dormir", "Manger", "Déguster", "Visiter".
Mais plutôt Hébergements, Musées, Restaurants, Produits du terroir...

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Correspond aux informations issues des Systèmes d'Informations
```suggestion
     - | Correspond aux animations pouvant être importées depuis des Systèmes d'Informations 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +       | catégories de type : animations, expositions, sorties…
```suggestion
       | catégories de type : conférences, expositions, sorties…
```
"animations" est un synonyme, pas une catégorie d'événements

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +       | formulaire dédié sur Geotrek-Rando
```suggestion
       | formulaire dédié sur Geotrek-rando
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Contient les informations saisies par un internautes via le
```suggestion
     - | Contient les problèmes remontés par les internautes, par exemple via le
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Permet de définir des sites (sites d'escalade, rivières, aires
```suggestion
     - | Permet de définir des sites d'activités de pleine nature (sites d'escalade, rivières, aires 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +       | des activités de pleines natures diverses (kayak, rafting,
```suggestion
       | des parcours de pleine nature diverses (kayak, rafting, 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +     - | Couplé au module « site outdoor», permet de saisir et renseigner
```suggestion
     - | Couplé au module « site outdoor», permet de les détailler en renseignant 
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +Les résultats sont affichés sous forme de liste puis on accède aux détails des objets.
```suggestion
Les résultats sont affichés sous forme de carte et liste puis on accède aux détails des objets.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +* une carte dans laquelle il est possible de naviguer (déplacer, zoomer), d'afficher en plein écran, de mesurer une longueur, d'exporter une image de la carte, de réinitialiser l'étendue, de zommer s
```suggestion
* une carte dans laquelle il est possible de naviguer (déplacer, zoomer), d'afficher en plein écran, de mesurer une longueur, d'exporter une image de la carte, de réinitialiser l'étendue, de zoomer sur une commune ou un secteur et de superposer des données des autres modules (contours communes / secteurs / physique / foncier / gestionnaires…)
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +* l'accès à la vue détail d'un objet au clic
```suggestion
* l'accès à la vue détail d'un objet au clic sur celui-ci
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/overview.rst
> +L’ajout, la modification ou la suppression des illustrations et photos s’effectuent depuis l’onglet « Fichiers liés » de la fiche détail.
```suggestion
L’ajout, la modification ou la suppression des documents, illustrations et photos s’effectuent depuis l’onglet « Fichiers liés » de la fiche détail.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +L’ajout, la modification ou la dé-publication sont fréquents.
Dé-publication fortement déconseillée pour le référencement et les passerelles vers les outils tiers, je ne la mentionnerai pas.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +Pour cela il faut créer un itinéraire parent (séjour itinérant complet) puis y ajouter des itinéraires enfants (étapes) de manière ordonnée, dans le champs `Enfants` présent dans l'onglet `Avancé` du
```suggestion
Pour cela il faut créer un itinéraire parent (séjour itinérant complet) puis y associer des itinéraires enfants (étapes) de manière ordonnée, dans le champs `Enfants` présent dans l'onglet `Avancé` du formulaire itinéraire du séjour complet.
```

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +- ``TREK_CATEGORY_ORDER = 1``
Je ne crois pas que ces paramètres soient encore utilisés.
Ils ne devaient servir que pour la synchro des données pour la V2 de Geotrek-rando.

Paragraphe à supprimer.

2024-01-23 22:56 UTC, camillemonchicourt commented on docs/usage/touristic-modules.rst
> +Si la randonnée intersecte une ou plusieurs zones zones de sensibilité, alors celles-ci sont affichées après les recommandations dans Geotrek-Rando.
```suggestion
Si une randonnée ou un site outdoor intersecte une ou plusieurs zones zones de sensibilité, alors celles-ci sont affichées après les recommandations dans Geotrek-Rando.
```

2024-01-24 13:51 UTC, camillemonchicourt reviewed
Je remets 4 suggestions qui avaient été validées mais ont ensuite sauté avec l'ajout d'URL il me semble.
Merci.

2024-01-24 13:51 UTC, camillemonchicourt commented on docs/about/geotrek.rst
> +* :ref:`Geotrek Admin <qu-est-ce-que-geotrek>`: outil de gestion et de saisie de l’ensemble des informations, intégrant les données des Systèmes d’Informations Touristiques (SIT) et pouvant se relier
```suggestion
* :ref:`Geotrek-admin <qu-est-ce-que-geotrek>`: outil de gestion et de saisie de l’ensemble des informations, intégrant les données des Systèmes d’Informations Touristiques (SIT) et pouvant être connecté à votre SIG ou à des systèmes d’information transport
```

2024-01-24 13:51 UTC, camillemonchicourt commented on docs/about/geotrek.rst
> +* `Geotrek Rando <https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/presentation-fr.md>`_ : site web, reprenant les informations saisies dans Geotrek Admin, à destination des internautes g
```suggestion
* `Geotrek-rando <https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/presentation-fr.md>`_ : site web, reprenant les informations saisies dans Geotrek-admin, à destination des internautes grand public
```

2024-01-24 13:51 UTC, camillemonchicourt commented on docs/about/geotrek.rst
> +* `Geotrek Mobile <https://github.com/GeotrekCE/Geotrek-mobile#geotrek-mobile>`_ : application mobile fonctionnant sous Android et iOS, reprenant des informations saisies dans Geotrek Admin et optimi
```suggestion
* `Geotrek-mobile <https://github.com/GeotrekCE/Geotrek-mobile#geotrek-mobile>`_ : application mobile fonctionnant sous Android et iOS, reprenant des informations saisies dans Geotrek-admin et optimisées pour l’usage mobile (volume, impact sur la batterie, hors-ligne, géolocalisation…)
```

2024-01-24 13:51 UTC, camillemonchicourt commented on docs/about/geotrek.rst
> +* `Geotrek Widget <https://github.com/GeotrekCE/Geotrek-rando-widget#geotrek-rando-widget>`_ : nouveau composant web permettant de valoriser une offre de contenus touristiques et de randonnées auprès
```suggestion
* `Geotrek-rando-widget <https://github.com/GeotrekCE/Geotrek-rando-widget#geotrek-rando-widget>`_ : nouveau composant web permettant de valoriser une offre de contenus touristiques et de randonnées auprès des usagers du territoire, en l'intégrant dans un site internet existant
```

2024-01-24 14:39 UTC, bruhnild commented on docs/usage/editing-objects.rst
> +Pour importer automatiquement des éléments de POIs, se référer à la section :ref:`Import DEM (altimetry) <import-dem-altimetry>`
My bad, c'est dû à un mauvais copier-coller. Je corrige.

2024-01-30 20:45 UTC, babastienne commented
@bruhnild gros boulot cette doc. Quitte à mettre les mains dans le truc autant aller jusqu'au bout. J'ai commencé à faire une review et finalement j'ai directement modifié les éléments en local sur mon poste. J'ai donc continué un peu, en reprenant certaines parties, en mettant à jour la configuration de la doc, changeant certains éléments, etc.

J'ai aussi enlevé la numérotation car ça me semblait être une mauvaise idée, je t'expliquerai pourquoi.

Il faut encore que je relise pas mal de fichiers, donc travail toujours en cours, pas fini de mon côté.

J'aimerai aussi qu'on puisse se pencher sur weblate pour être sur que c'est à jour, et j'aimerai qu'on réfléchisse à la traduction de la doc.

J'ai ajouté quelques commits. Ca serait bien de ne pas tout fusionner au moment de merger car il faudra garder une trace avec une granularité plus fine que "toute la PR" vu que j'ai touché à pas mal de choses et qu'on est maintenant deux  travailler sur cette PR. Il faudrait donc faire le tri dans tes commits et fusionner ceux qui peuvent l'être, j'ai déjà commencé mais il y en a surement d'autres à faire.

A suivre ...

2024-02-28 10:33 UTC, babastienne requested changes
Est-ce possible de vérifier que toutes les images présentes dans /docs/images sont bien utilisées quelque part dans le doc ? S'il y a des images non utilisées il faudrait les retirer.

2024-02-28 10:33 UTC, babastienne commented on docs/about/geotrek.rst
> +* `Geotrek-rando-widget <https://github.com/GeotrekCE/Geotrek-rando-widget#geotrek-rando-widget>`_ : nouveau composant web permettant de valoriser une offre de contenus touristiques et de randonnées
```suggestion
* `Geotrek-rando-widget <https://geotrek-rando-widget.readthedocs.io/>`_ : nouveau composant web permettant de valoriser une offre de contenus touristiques et de randonnées auprès des usagers du territoire, en l'intégrant dans un site internet existant
```

2024-02-28 10:33 UTC, babastienne commented on docs/about/geotrek.rst
> +* **JavaScript / React**, **Next.js**, **Leaflet**, **SVG** et **WebGL** pour l'interaction avec les utilisateurs et la visualisation, **HTML5** pour la structure du site, **CSS3** pour l’apparence.
React / NextJS n'est utilisé que dans Geotrek-Rando V3. Est-ce que dans cette section on indique les technnologies de toute la suite logicielle Geotrek ou uniquement GTA ? 
- Si uniquement GTA : retirer les infos relatives à Next JS et React
- Si tout la stack alors ajouter des infos relatives à Mobile et Widget.

2024-02-28 10:33 UTC, babastienne commented on docs/contribute/contributing.rst
> +Join the `mailing list <https://groups.google.com/forum/#!forum/geotrek-fr>`_! Send an email to ``geotrek-fr+subscribe@googlegroups.com`` and you will receive an invitation automatically.
Est-ce que cette ligne ne peut pas être mise ailleurs dans la documentation, dans une section dédiée : communauté peut-être ? Dedans on indiquerai les différentes manière de joindre la communauté, via la mailing liste, les chans Matrix, etc ?

Je verrai bien deux sections supplémentaires dans le fichier "Présentation générale de Geotrek" : 
- Une section "A qui appartient Geotrek ?", où on aurai la possibilité d'écrire un petit texte sur le fait que c'est libre (d'utiliser, copier, modifier, diffuser, etc.) / qui a financé à l'origine le produit / plusieurs sociétés ont contribué au développement -> ca n'appartient pas à une société
- Une section "Comment joindre / intégrer la communauté ?" : qui explique les moyens de communiquer avec la communauté (voir le début de ce commentaire).

Pour moi ces deux sections auront leur place entre la section "Utilisateurs" et "Composants libres"

2024-02-28 16:07 UTC, babastienne commented on docs/usage/configuration-ttw.rst
> +* Avoir une dimension minimale de 6.x6. pixels en ce qui concerne les PNG
```suggestion
* Avoir une dimension minimale de 56x56 pixels en ce qui concerne les PNG
```

2024-02-28 16:17 UTC, babastienne commented on docs/about/geotrek.rst
> +Retrouvez toutes les infos sur la genèse du produit, son modèle communautaire ainsi que les principales sociétés contributrices sur le site `geotrek.fr <https://geotrek.fr/apropos.html>`_.
```suggestion
Retrouvez toutes les infos sur la genèse du produit, son modèle communautaire ainsi que les principales structures contributrices sur le site `geotrek.fr <https://geotrek.fr/apropos.html>`_.
```

2024-02-28 16:17 UTC, babastienne commented on docs/about/geotrek.rst
> +* Corrigez des bugs ou améliorez les modules de base (*nécessite des compétences python/Django*)
Pour le coup toute cette partie j'aurai conservé dans "Contributing", car c'est une manière de contribuer au projet.

Dans cette section "Comment rejoindre la communauté", je verrai : 
- La ligne que tu as insérée ci-dessous
- Eventuellement les lignes "ouvrir un ticket" bug + feature
- Une ligne sur le canal de discussion Matrix, avec un lien vers le canal. Inspire toi de [ce mail](https://groups.google.com/g/geotrek-fr/c/shn0jOLvjDc)

2024-02-28 22:07 UTC, babastienne approved these changes

2024-02-28 22:11 UTC, merged