Improve troubleshouting section with Document / Map capture generation
GeotrekCE/Geotrek-admin pull request #3891
Opened 2024-01-17 15:34 UTC by submarcos

## Description

## Related Issue

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/CONTRIBUTING.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation](https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2024-01-17 15:44 UTC, camillemonchicourt approved these changes

2024-01-18 09:20 UTC, Chatewgne requested changes

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +But if Geotrek-admin does not start, take a look to systemd logs for each of the 3 Geotrek-admin services
```suggestion
But if Geotrek-admin does not start, take a look at systemd logs for each of the 3 Geotrek-admin services
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +Type Q to quit. If you want to copy the log to a file, do:
```suggestion
Type Q to quit. If you want to copy the log to a file, run:
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +Frequent problems encountered
```suggestion
Frequently encountered problems
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +   Faites attention aux pares-feux, proxy et domaine privés. L'hôte (ou le container docker) doit pouvoir correctement résoudre l'adresse IP du domaine utilisé.
```suggestion
   Faites attention aux pare-feux, proxy et domaines privés. L'hôte (ou le container docker) doit pouvoir correctement résoudre l'adresse IP du domaine utilisé.
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +- l'IP derriere le domaine demo-admin.geotrek.fr depuis mon poste de travail est 88.77.66.55, il s'affiche bien, mais depuis le serveur c'est 172.16.0.10, les captures de carte ne fonctionnent pas. I
```suggestion
- l'IP derriere le domaine demo-admin.geotrek.fr depuis mon poste de travail est 88.77.66.55, il s'affiche bien, mais depuis le serveur c'est 172.16.0.10, les captures de carte ne fonctionnent pas. Il faut jouer avec la configuration de la machine, les serveurs DNS, les paramètres network/alias ou extra_hosts du docker-compose.yml afin de le rendre accessible.
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +- le Proxy qui gère les certificats SSL ne transmet pas les bons en-tête à geotrek-admin. De ce fait, geotrek-admin pense tourner en http et génère des url en http:// à screamshotter (ex: prend une c
```suggestion
- le Proxy qui gère les certificats SSL ne transmet pas les bons en-têtes à geotrek-admin. De ce fait, geotrek-admin pense tourner en http et génère des url en http:// à screamshotter (ex: prend une capture de http://mon-geotrek-admin.fr/trek/1/ au lieu de https://mon-geotrek-admin.fr/trek/1/). Il faut penser à bien transmettre l'en-tête **X-Forwarded-Proto https** .
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +Si çà ne fonctionne pas, vérifiez le message d'erreur :
```suggestion
Si ça ne fonctionne pas, vérifiez le message d'erreur :
```

2024-01-18 09:20 UTC, Chatewgne commented on docs/troubleshooting.rst
> +On peut voir que l'URL est **http** et non **https**, c'est un problème d'en-tête non transmis. Il faut régler çà au niveau du proxy.
```suggestion
On peut voir que l'URL est **http** et non **https**, c'est un problème d'en-tête non transmis. Il faut régler ça au niveau du proxy.
```

2024-01-19 08:56 UTC, submarcos commented on docs/troubleshooting.rst
> +-----------------------------
```suggestion
-------------------------------
```

2024-01-19 09:05 UTC, merged