[TOOLS] Update all trad files
GeotrekCE/Geotrek-admin pull request #3930
Opened 2024-02-09 14:09 UTC by juggler31

## Description

## Related Issue

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/CONTRIBUTING.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation](https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2024-02-09 14:39 UTC, submarcos commented on geotrek/api/locale/fr/LC_MESSAGES/django.po
> +#, fuzzy
fuzzy significate that django has tried to translate itmself. Please check and correct translate, then delete fuzzy reference

2024-02-12 13:45 UTC, marcantoinedupre requested changes
Nice work! I have spotted a few changes which looks unrelated.

2024-02-12 13:45 UTC, marcantoinedupre commented on geotrek/trekking/tests/data/file_bad_encoding_tmp.kml
Why has this file changed?

2024-02-12 13:45 UTC, marcantoinedupre commented on geotrek/trekking/tests/data/file_good_encoding_tmp.kml
Same here: why has this file changed?

2024-02-12 13:45 UTC, marcantoinedupre commented on Makefile
Unrelated? Or maybe in another commit at least?

2024-02-12 15:35 UTC, marcantoinedupre approved these changes

2024-02-14 10:43 UTC, submarcos commented on docs/changelog.rst
> +- Update all message files
```suggestion
- Update all translation files
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/api/locale/fr/LC_MESSAGES/django.po
>  "Ce champ est déprécié et sera retiré dans de prochaines releases, merci "
```suggestion
"Ce champ est déprécié et sera retiré dans une future version, merci "
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/tourism/locale/fr/LC_MESSAGES/django.po
> +msgstr ""
```suggestion
msgstr "Signalétiques"
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/signage/locale/fr/LC_MESSAGES/django.po
> +msgstr ""
translation is missing

2024-02-14 10:43 UTC, submarcos commented on geotrek/signage/locale/fr/LC_MESSAGES/django.po
> +msgstr ""
translation is missing

2024-02-14 10:43 UTC, submarcos commented on geotrek/signage/locale/fr/LC_MESSAGES/django.po
> +msgstr "Pictogramme des lignes"
```suggestion
msgstr "Pictogramme de ligne"
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/signage/locale/fr/LC_MESSAGES/django.po
> +msgstr "Pictogrammes des lignes"
```suggestion
msgstr "Pictogrammes de ligne"
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/signage/locale/fr/LC_MESSAGES/django.po
> +msgstr "Filtrer par un ou plusieurs gestionnaires."
```suggestion
msgstr "Filtrer par un ou plusieurs gestionnaires."
```

bad translation

2024-02-14 10:43 UTC, submarcos commented on geotrek/maintenance/locale/fr/LC_MESSAGES/django.po
> +#| msgid "Begin date is after end date"
fuzzy !

2024-02-14 10:43 UTC, submarcos commented on geotrek/feedback/locale/fr/LC_MESSAGES/django.po
> +msgstr ""
```suggestion
msgstr ""
```

missing translation

2024-02-14 10:43 UTC, submarcos commented on geotrek/common/locale/fr/LC_MESSAGES/django.po
>  msgstr "%(obj)s a changé d'état, et a besoin d'être review pour être publié."
```suggestion
msgstr "%(obj)s a changé d'état, et a besoin d'être validé pour être publié."
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/common/locale/fr/LC_MESSAGES/django.po
>  msgstr "Geotrek Admin"
```suggestion
msgstr ""
```

2024-02-14 10:43 UTC, submarcos commented on geotrek/common/locale/fr/LC_MESSAGES/django.po
> +
missing translation

2024-02-16 11:18 UTC, merged