feat: change infrastructure condition field to ManyToMany field (#3970)
GeotrekCE/Geotrek-admin pull request #4084
Opened 2024-04-26 14:50 UTC by juggler31

## Description

## Related Issue

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/contribute/contributing.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation](https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2024-04-29 12:42 UTC, submarcos commented on geotrek/infrastructure/tests/factories.py
> +                obj.conditions.add(InfrastructureConditionFactory.create())
can you factorize post_generation in an InfrastructureFatoyMixin ?

2024-04-30 11:53 UTC, Chatewgne requested changes

2024-04-30 11:53 UTC, Chatewgne commented on geotrek/infrastructure/migrations/0039_infrastructure_conditions.py
> +        infrastructure.conditions.add(infrastructure.condition)
Fails if we have an infrastructure with no Condition

2024-05-22 08:57 UTC, Chatewgne approved these changes

2024-05-22 09:45 UTC, marcantoinedupre commented on geotrek/infrastructure/models.py
> +            conditions_list = self.conditions_list
Je propose de ne pas utiliser l'attribut `conditions_list`. Il introduit une sorte de dépendance du modèle vers la view mais après test je ne constate pas d'amélioration des perfs en utilisant le param `to_attr` de `Prefetch` dans la View et le nb de requêtes SQL est le même (test avec 5000 aménagements).

2024-05-22 12:55 UTC, submarcos commented on geotrek/infrastructure/models.py
> +            conditions_list = self.conditions_list
dans ce cas il faut trouver un moyen de factoriser car il faut que le prefetch soit utilisé par les vues interne mapentity drf zet les exports csv shape etc...

Par contre je ne sais pas comment tu as testé mais le prefecth fonctionne tres bien chez moi

2024-05-22 12:56 UTC, submarcos commented on geotrek/infrastructure/models.py
> +            conditions_list = self.conditions_list
avec : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/7448208/5b2a6d0c-43a7-4bbf-b33d-d08c178b89db)

sans :
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/7448208/417fcd5d-52db-4a19-b25b-a0f123d26280)

2024-07-19 09:19 UTC, submarcos commented on docs/changelog.rst
> +
```suggestion
```

2024-07-19 09:20 UTC, submarcos commented on docs/changelog.rst
```suggestion

```

2024-07-19 09:22 UTC, submarcos commented on docs/changelog.rst
> +- Change infrastructure condition field to ManyToMany field (#3970)
```suggestion
- Change infrastructure condition field to ManyToMany field (#3970)

```

2024-07-19 09:22 UTC, submarcos commented on docs/changelog.rst
> +
```suggestion
```

2024-07-19 09:22 UTC, submarcos commented on docs/changelog.rst
```suggestion


```

2024-07-23 12:04 UTC, merged