fix flaky translation test
GeotrekCE/Geotrek-admin pull request #4348
Opened 2024-10-22 13:30 UTC by submarcos

## Description

## Related Issue

## Checklist

- [ ] I have followed the guidelines in our [Contributing document](https://geotrek.readthedocs.io/en/latest/contribute/contributing.html)
- [ ] My code respects the Definition of done available in the [Development section of the documentation](https://geotrek.readthedocs.io/en/latest/contribute/development.html#definition-of-done-for-new-model-fields)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes
- [ ] I added an entry in the changelog file
- [ ] My commits are all using prefix convention (emoji + tag name) and references associated issues
- [ ] I added a label to the PR corresponding to the perimeter of my contribution
- [ ] The title of my PR mentionned the issue associated

2024-11-05 16:08 UTC, Chatewgne requested changes

2024-11-05 16:08 UTC, Chatewgne commented on geotrek/infrastructure/tests/test_parsers.py
> +    @override_settings(MODELTRANSLATION_DEFAULT_LANGUAGE="fr", LANGUAGE_COE="fr")
```suggestion
    @override_settings(MODELTRANSLATION_DEFAULT_LANGUAGE="fr", LANGUAGE_CODE="fr")
```

2024-11-06 10:06 UTC, submarcos commented on geotrek/common/middleware.py
> +    request.GET.get('lang')
good point. fixed

2024-11-06 10:27 UTC, submarcos commented on geotrek/cirkwi/tests/test_views.py
> +        self.maxDiff = None
fixed

2024-11-06 10:27 UTC, submarcos commented on geotrek/cirkwi/tests/test_views.py
> +        self.maxDiff = None
fixed

2024-11-06 10:27 UTC, submarcos commented on geotrek/infrastructure/tests/test_parsers.py
> +    @override_settings(MODELTRANSLATION_DEFAULT_LANGUAGE="fr", LANGUAGE_COE="fr")
fixed

2024-11-06 11:03 UTC, merged